parser: "@typescript-eslint/parser"
extends:
  - plugin:type-graphql/recommended
  - plugin:react-hooks/recommended
plugins:
  - "type-graphql"
parserOptions:
  project: "./tsconfig.json"
settings:
  react:
    version: detect
ignorePatterns:
  - "lib/graphqlClient.ts"
