require:
  - ts-node/register
schema: http://localhost:3000/api/graphql
documents: "pages/**/*.graphql"
generates:
  ./lib/graphqlClient.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql
    config:
      withHooks: true
      strictScalars: true
      defaultScalarType: unknown
      immutableTypes: true
